# Generated by Django 5.0.6 on 2024-06-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='visitor',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
